services:
  - type: web
    name: igpc-live-system
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    autoDeploy: true
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: NODE_ENV
        value: production
